const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
(async()=>{
 const prefs=new Map(),notes=new Map(),records=new Map();let created=0;
 const item={id:3,libraryID:1,isAttachment:()=>false,getField:()=> 'Paper'};
 const ctx=vm.createContext({AbortController,setTimeout,clearTimeout,console,Zotero:{Prefs:{get:key=>prefs.get(key),set:(key,value)=>prefs.set(key,value)},Items:{get:id=>id===3?item:notes.get(id)},logError(){}}});
 for(const file of ['main.js','batch.js'])vm.runInContext(fs.readFileSync('plugin_src/chrome/content/scripts/'+file,'utf8'),ctx);
 ctx.TaskCheckpointCache={get:async key=>records.get(key),put:async(key,record)=>records.set(key,record)};
 records.set('checkpoint',{resumeKey:'summary:1:PDF',final:'answer'});
 ctx.ZoteroAdapter={createChildNote:async()=>{created++;await Promise.resolve();const note={id:created+100,libraryID:1,parentID:3,isNote:()=>true};notes.set(note.id,note);return note;}};
 const result={targetItem:item,markdown:'answer',title:'Paper',promptType:'paper_summary',checkpointKey:'checkpoint'};
 const both=await Promise.all([ctx.ZoteroMinerUAI.saveSummary(result),ctx.ZoteroMinerUAI.saveSummary(result)]);
 assert.equal(created,1);assert.equal(both[0].id,both[1].id);
 vm.runInContext(fs.readFileSync('plugin_src/chrome/content/scripts/main.js','utf8'),ctx);
 await ctx.ZoteroMinerUAI.saveSummary(result);assert.equal(created,1,'restored completed result must reuse its existing note');
 notes.get(both[0].id).deleted=true;await ctx.ZoteroMinerUAI.saveSummary(result);assert.equal(created,2,'deleted notes must be safely recreated');
 const savedGet=ctx.TaskCheckpointCache.get;let cacheRelease;
 ctx.TaskCheckpointCache.get=async()=>new Promise(resolve=>cacheRelease=resolve);
 const saveController=new AbortController();const waitingSave=ctx.ZoteroMinerUAI.saveSummary(result,{signal:saveController.signal});
 await new Promise(resolve=>setTimeout(resolve,0));saveController.abort();cacheRelease(null);
 await assert.rejects(waitingSave,error=>error.name==='AbortError');assert.equal(created,2,'pause before note creation must not write a new note');
 ctx.TaskCheckpointCache.get=savedGet;

 let controller=new AbortController(),processed=[],saved=[],events=[];
 ctx.ZoteroAdapter={getPdfAttachment:async row=>({filePath:'paper.pdf',attachmentItem:row})};
 const app=ctx.ZoteroMinerUAI;app.saveSummaryPrompt=()=>{};
 app.summarizeItem=async(row,type,report,config,prompt,{signal})=>{processed.push(row.id);if(row.id===3){controller.abort();const error=Error('paused');error.name='AbortError';throw error;}return {targetItem:row,markdown:'summary'};};
 ctx.Zotero.Items.get=id=>({id,libraryID:1,getField:()=>`Paper ${id}`});
 app.saveSummary=async value=>{saved.push(value.targetItem.id);return {id:200};};
 let totals=JSON.parse(await ctx.SIBatch.run(app,[1,3,5],'paper_summary',{llmSlot:1,llmMaxTokens:8192},'prompt',json=>events.push(JSON.parse(json)),()=>false,{signal:controller.signal}));
 assert.equal(totals.completed,1);assert.equal(totals.stopped,2);assert.deepEqual(saved,[1]);
 assert.deepEqual(Array.from(app.getBatchQueue().pendingIDs),[3,5]);assert.equal(app.getBatchQueue().status,'paused');
 vm.runInContext(fs.readFileSync('plugin_src/chrome/content/scripts/main.js','utf8'),ctx);
 const restored=ctx.ZoteroMinerUAI;restored.saveSummaryPrompt=()=>{};restored.summarizeItem=async row=>({targetItem:row,markdown:'summary'});restored.saveSummary=app.saveSummary;
 const queue=restored.getBatchQueue();totals=JSON.parse(await ctx.SIBatch.run(restored,queue.pendingIDs,queue.type,{llmSlot:1,llmMaxTokens:8192},queue.prompt));
 assert.equal(totals.completed,2);assert.deepEqual(saved,[1,3,5]);assert.equal(restored.getBatchQueue().pendingIDs.length,0);
 // Exercise real checkpoint keys and highlight loops while keeping PDF/database I/O in memory.
 for(const file of ['task_checkpoints.js','llm_client.js','auto_highlight.js'])vm.runInContext(fs.readFileSync('plugin_src/chrome/content/scripts/'+file,'utf8'),ctx);
 ctx.SIError={describe:e=>e.message};ctx.Zotero.Libraries={get:()=>({editable:true})};
 const attachment={id:8,key:'PDF',libraryID:1,deleted:false};
 ctx.ZoteroAdapter={getPdfAttachment:async()=>({filePath:'paper.pdf',attachmentItem:attachment})};
 let writes=0,transactions=0,abortDuringWrite=false;
 ctx.Zotero.DB={executeTransaction:async callback=>{transactions++;const previous=writes;try{await callback();}catch(error){writes=previous;throw error;}}};
 const highlight=ctx.AutoHighlight;
 highlight.readPDF=async()=>[{chars:[{c:'text'}]}];
 highlight.indexPages=()=>({text:'source text',total:20000,sentences:[{id:0,text:'a'.repeat(8000)},{id:1,text:'b'.repeat(8000)}]});
 highlight.existing=()=>[];highlight.select=()=>[{weight:100,text:'highlight'}];
 highlight.saveHighlightInTransaction=async()=>{writes++;if(abortDuringWrite)controller.abort();};
 const config={llmApiBase:'http://localhost:11434/v1',llmModel:'test',llmProvider:'custom',llmSlot:1};
 controller=new AbortController();let calls=0;
 ctx.LLMClient.complete=async(messages,cfg,{signal})=>{calls++;const group=JSON.parse(messages[1].content);if(group[0].id===1){controller.abort();const error=Error('paused');error.name='AbortError';throw error;}return JSON.stringify([{start:0,end:0,quote:'a',category:'结论'}]);};
 await assert.rejects(()=>highlight.run(item,config,()=>{},{signal:controller.signal}),e=>e.name==='AbortError');assert.equal(calls,2);assert.equal(transactions,0);assert.equal(writes,0);assert.equal(highlight.running.size,0);
 controller=new AbortController();calls=0;
 ctx.LLMClient.complete=async(messages)=>{calls++;const group=JSON.parse(messages[1].content);return JSON.stringify([{start:group[0].id,end:group[0].id,quote:'text',category:'结论'}]);};
 await highlight.run(item,config,()=>{},{signal:controller.signal});assert.equal(calls,1,'completed first highlight group must be reused');assert.equal(writes,1);
 controller=new AbortController();abortDuringWrite=true;
 await assert.rejects(()=>highlight.run(item,config,()=>{},{signal:controller.signal}),e=>e.name==='AbortError');assert.equal(writes,1,'pause during transaction must roll back every new annotation');
 console.log('task integration passed: saved-result deduplication, deleted-note recovery, queue restart, highlight group resume and cancellation rollback');
})().catch(e=>{console.error(e);process.exitCode=1;});
